services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    volumes:
      - /sharedfolders/dev/config/jellyfin:/config
      - /sharedfolders/dev/cache/jellyfin:/cache
      - /hdd-almond-10tb/movies:/media/movies
      - /hdd-almond-10tb/tv:/media/tv
      - /hdd-almond-10tb/music:/media/music
      - /hdd-almond-10tb/photos:/media/photos
      - /hdd-almond-10tb/videos:/media/videos
    restart: unless-stopped
